### ISSUE TITLE
Eat Food but not change length and size

### ISSUE THREAD

**Issue by jeozey** [gegy1000/Slyther#12]
Build Your lastest version,and run client to server 127.0.0.1:444
Event the protocol is not the same as slither.io now,
but i hope your client and server are ok alone.

**Comment by Gegy** [comment]
The server is not finished yet.

**Comment by jeozey** [comment]
no,maybe i did not explain correct.
I mean i run client and server , connect success and show snake and food,
and snake can eat food,but snake can not get longer or bigger.
I donot know why.

**Comment by Gegy** [comment]
You did explain correct. The server is not finished yet.

**Comment by jeozey** [comment]
Sorry,I can not understand what your mean.

**Comment by jeozey** [comment]
ok, waitting for you,hope i could pull request one day

**Comment by jeozey** [comment]
That would be better if you write a todo list in readme.
Thanks
