### ISSUE TITLE
black window before first resizing

### ISSUE THREAD

**Issue by Mat2095** [gegy1000/Slyther#3]
When I run the client, the window stays black (with a grey rectangle?) until I resize it:
![bildschirmfoto von 2016-05-31 15-57-10](https://cloud.githubusercontent.com/assets/11258252/15677025/c7e4b80c-2748-11e6-8df0-ab3f8c046482.png)

**Comment by pau101** [comment]
What does the console show? Any errors?

**Comment by GrumpyOet** [comment]
its show this 

```
INFO:Use Java PNG Loader = true
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

```

**Comment by GrumpyOet** [comment]
i think you have need to add log4j-core-2.0.jar to the classpath

**Comment by pau101** [comment]
@GrumpyOet are you experiencing the black screen?

**Comment by Mat2095** [comment]
I do get the Java-PNG-Loader info, then the pinger info. After I close the frame, I get an exception, but it is something with gradle, I'll look further into it.
I only get the black frame on Linux, not Windows.

**Comment by Mat2095** [comment]
[This](https://github.com/gegy1000/Slyther/blob/master/src/main/java/net/gegy1000/slyther/client/SlytherClient.java#L296) `System.exit(1);` is called (it's not a gradle problem, I was wrong there) when I close the frame.
It is also called when I first resize it, so it is displayed correctly, so I don't know if this is related.

**Comment by Mat2095** [comment]
I can confirm that both the black screen and the exception are gone. Thanks :)
