### ISSUE TITLE
Build Failiure

### ISSUE THREAD

**Issue by Qasimmodo** [gegy1000/Slyther#6]
root@re:~/Slyther# gradle build

FAILURE: Build failed with an exception.
- Where:
  Build file '/root/Slyther/build.gradle' line: 1
- What went wrong:
  A problem occurred evaluating root project 'Slyther'.
  
  > Could not find method plugins() for arguments [build_2i0huu3jnn03jk7ltodn3e233$_run_closure1@73802b40] on root project 'Slyther'.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.245 secs

**Comment by pau101** [comment]
You're running an old version of Gradle, updating should resolve the problem.
