### ISSUE TITLE
Select server

### ISSUE THREAD

**Issue by GrumpyOet** [gegy1000/Slyther#7]
if you make the pictures 3 times (not 128x128 but 384x384) bigger and shrink it 3x in the java code
or
you make them 2 times bigger than the actual size in the game and shrink it 2x

or how many times you need to shrink it

**Comment by GrumpyOet** [comment]
Gegy1000 do you have an idea to give it a better resolution (if my idea not works)

**Comment by Gegy** [comment]
Is there a need for higher resolution?

**Comment by GrumpyOet** [comment]
I see the corners

**Comment by GrumpyOet** [comment]
The eyes and the begin screen (play button)

**Comment by Gegy** [comment]
The eyes aren't rendered with textures - and they don't have anti-aliasing, so they don't look high-quality. I'll improve the buttons, though.

**Comment by GrumpyOet** [comment]
Ok thanks

**Comment by GrumpyOet** [comment]
Maybe you can make the eyes with pictures like the jelly skin

**Comment by GrumpyOet** [comment]
Can u make select server work than can i connect to slither server

**Comment by Gegy** [comment]
The higher resolution images have been done.

**Comment by Gegy** [comment]
http://i.imgur.com/0IWOFkP.png
