### ISSUE TITLE
build server

### ISSUE THREAD

**Issue by MattyIce2002** [gegy1000/Slyther#8]
for some reason the server wont build with gradle
gradle build
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Configuration on demand is an incubating feature.
:compileJava
Note: C:\Users\Matthew.Stegink\Desktop\d\Slyther-master\src\main\java\net\gegy1000\slyther\server\SlytherServer.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources
:classes
:jar
:startScripts
:distTar
:distZip
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

**Comment by Gegy** [comment]
"BUILD SUCCESSFUL"? Looks like it built fine? Also, the server is not finished yet.

**Comment by yarhoslavme** [comment]
Excellent Project!!!.  Great work!.  is there any documentation or specific task you need for finish the server?  I will love contribute with the project.  Thank you.

**Comment by Gegy** [comment]
Well, documentation is not needed yet. Currently the server only handles the leaderboard and snake movement. Food eating, preys and map all need to be done still.
